### ISSUE TITLE
deploy with cf push

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [gregorwolf/bookshop-nodejs#1]
why are there 02 server.js?

in which folder should I run cf push: / or / srv?

**Comment by gregorwolf** [comment]
The one in / is for local development. For deployment to SAP CP Cloud Foundry you should use the MTA. I've just updated the project and you find now the scripts build:cf and deploy:cf in the package.json

**Comment by luizcarlospedrosogomes** [comment]
update srv/packge.json
![image](https://user-images.githubusercontent.com/9791364/75147016-1f3adf80-56db-11ea-9d39-c76fba6224b7.png)

run cf push


erros
1 -  not find table

2 - url nodesjs not working
![image](https://user-images.githubusercontent.com/9791364/75147649-93c24e00-56dc-11ea-8656-19f62e984e2a.png)

**Comment by gregorwolf** [comment]
It seems to me you haven't pulled my latest changes. As this app consists of a db, srv and app module a `cf push` will not work.

**Comment by luizcarlospedrosogomes** [comment]
this is structure my project. I dont use app, my project is a API.
![image](https://user-images.githubusercontent.com/9791364/75153715-d1c66e80-56ea-11ea-8aac-918d072255d8.png)

 I update script srv/package.json conform image
https://user-images.githubusercontent.com/9791364/75147016-1f3adf80-56db-11ea-9d39-c76fba6224b7.png

**Comment by gregorwolf** [comment]
Please try to get first my project deployed. Then you can ask further.
