### ISSUE TITLE
Error deploy SCP

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [gregorwolf/bookshop-nodejs#2]
![image](https://user-images.githubusercontent.com/9791364/75635152-846a6580-5bf2-11ea-846c-3a13191b73b7.png)

[INTERNAL ERROR] SyntaxError: Invalid regular expression: /^(?:(?:_|\p{Letter}|\p{Letter_Number})(?:_|\p{Letter}|\p{Letter_Number}|\p{Decimal_Number}|\p{Nonspacing_Mark}|\p{Spacing_Mark}|\p{Connector_Punctuation}|\p{Format}){0,127})/: Invalid escape

**Comment by gregorwolf** [comment]
Have you tried with the 3.21.3 version of @sap/cds? The latest release currently has some issues.

**Comment by luizcarlospedrosogomes** [comment]
tanks @gregorwolf. updated to 3.21.1 using npm install but nor working. Now update to 3.21.3 and working

**Comment by luizcarlospedrosogomes** [comment]
new error
![image](https://user-images.githubusercontent.com/9791364/75685338-30569400-5c79-11ea-841f-a0d4965838fd.png)

ERR [INTERNAL ERROR] TypeError: server_js is not a function


Do I need to update any more packages?

**Comment by gregorwolf** [comment]
Just to link for reference: https://github.com/SAP-samples/cloud-cap-samples/issues/30
